"""
Build multi-file GitHub Pages dashboard site.

Produces a directory with:
  index.html          - lean dashboard (no inlined data/images)
  data/bids.sqlite    - SQLite database for the whole page (bids, zones, waterbody
                        BIDs, Scoring Lab sample polygons, solar percentiles)

Run:  python build_client_site.py
"""
import os, csv, shutil, json, sqlite3, time, sys, gzip, hashlib, glob

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MD_DIR = r"U:\GIS\temp\CS\RS\Nook\RF_Test\MD"

# --- Input paths ---
HTML_PATH = os.path.join(SCRIPT_DIR, "client_dashboard.html")
MAIN_JSON = os.path.join(MD_DIR, "dashboard_data.json")
BID_JSON  = os.path.join(MD_DIR, "bid_explorer_data.json")

# BID_Scores_Calculated_20260507.csv -- NEW build input (not part of the RF_Test tree).
#
# Why this exists: the shipped dashboard displays rpsf (RP_S_final, the S-curve score)
# but until now the "Score breakdown" card was built from the LINEAR track's components
# (rp = RP_norm, sol/slp = linear pushes), because the upstream bid_explorer_data.json
# export never included RP_S_norm (the S-curve base). Mixing a linear base+pushes with
# an S-curve total is a score-integrity bug: the rows didn't add up to the total shown.
#
# This CSV (one row per BID, joined 1:1 on BID against the bids table) supplies the
# missing RP_S_norm plus solar_risk/slope_risk/wetland_push, from which the true S-track
# pushes are computed below. It also supplies RP_S_final and RP_S_area_pctile (rpsf/rpsa)
# directly, rather than taking those two from the upstream JSON: the JSON and this CSV
# are independently-rounded exports of the same underlying computation, so the whole
# S-track (rpsn/sols/slps/rpsf/rpsa) is sourced from this one CSV to make
# rpsn + sols + slps + wet == rpsf hold exactly instead of to within rounding. The proper
# long-term fix is to add RP_S_norm (and/or the S-track pushes directly) to
# preprocess_dashboard.py's JSON export the next time that tree is editable (it lives
# under the read-only RF_Test path and cannot be touched from here) -- at that point this
# CSV join can be removed.
SCORES_CSV = os.path.join(SCRIPT_DIR, "BID_Scores_Calculated_20260507.csv")
EXPECTED_SCORE_ROWS = 30850

# BID_ZID_LC_20260501.csv -- polygon-level landcover source (596,981 rows, ~432 MB).
#
# Why this exists: zones.ht (shipped as the "Canopy height by buffer zone" chart)
# is mean(ForestHeight) computed upstream, but ForestHeight is a full-polygon mean
# ("NOT tree-only" per the methods doc) -- averaging it in is fine for the intactness
# score, which is a full-polygon concept, but wrong for a chart labeled "Canopy height",
# which should reflect trees only. This CSV supplies the row-level fields needed to
# recompute a genuine forest-only canopy height per (BID, zone):
#   Height_for_M = CanopyHeight if present else ForestHeight   (preprocess_dashboard.py:349)
#   zone_cht = SUM(Height_for_M * SQFT) / SUM(SQFT)  over Forest polygons only
# Replicated exactly from preprocess_dashboard.py (read-only, under RF_Test) are:
#   1. the Forest -> Shrub/Woodland reclassification for any polygon with non-null
#      Composition AND 0 < ForestHeight <= 12 ft (lines ~271-279)
#   2. the Waterbody BID exclusion (PositionWaterbody == "Waterbody", lines ~322-329)
#   3. the Zone string -> zones.z integer mapping (ZONE_ORDER, lines 35-36)
# The result is validated against the existing zones.lc0 * sqft (Forest area per
# BID+zone, computed upstream after the same reclassification) -- see
# compute_zone_canopy_height() below.
LC_CSV = os.path.join(SCRIPT_DIR, "BID_ZID_LC_20260501.csv")

# Cached output of the two passes over BID_ZID_LC_20260501.csv (432 MB, not committed).
# The cache is small (a few MB), committed, and is what the build normally reads. Pass
# --refresh-lc-cache to rebuild it from the CSV (needed only if the CSV changes).
LC_CACHE = os.path.join(SCRIPT_DIR, "data_cache", "lc_derived_20260501.json")
REFRESH_LC_CACHE = False  # set by main() from --refresh-lc-cache
ZONE_TO_IDX = {"50": 0, "100": 1, "300": 2, "hmz": 3, "hmz300": 4}
RECLASS_MAX_HT = 12.0  # ForestHeight <= this (and > 0) with non-null Composition -> not Forest

# Landcover class order for the 9-slot proportion arrays (zones table, and the
# waterbody_bids `lc` array below). Must match LC_ORDER in preprocess_dashboard.py
# (~line 1898), which itself must match LAB_LC_KEYS in dashboard.html.
LC_ORDER = [
    "Forest", "Shrub/Woodland", "Shrub", "Ground/Herbaceous",
    "Impervious", "Canopy over Impervious", "Water",
    "Gravel/Abandoned Channel", "Railway",
]
LC_INDEX = {lc: i for i, lc in enumerate(LC_ORDER)}

# fish_access_override.csv -- Fix 1: the GIS feature layer (TP_Split_JOIN_20260507.csv)
# is authoritative for fish access, not the May-7 scoring table's Fish_simple pull.
# This override file is generated by tools/make_fish_override.py (a one-off script,
# not part of this build) and lists every BID where the two disagree. See that
# script's docstring and the "Fish access correction" section of
# CLIENT_DASHBOARD_NOTES.md for the full story.
FISH_OVERRIDE_CSV = os.path.join(SCRIPT_DIR, "data_overrides", "fish_access_override.csv")

# ---------- Priority tiers ----------
# Reimplemented EXACTLY from assign_tier() in preprocess_dashboard.py (~lines 1306-1330),
# read-only under RF_Test. First matching rule wins.
NOOKSACK_ZONES = {
    "Lower Mainstem Nooksack", "Upper Mainstem Nooksack",
    "Lower NF Nooksack", "Upper NF Nooksack",
    "Lower MF Nooksack", "Upper MF Nooksack",
    "Lower SF Nooksack", "Upper SF Nooksack",
}


def assign_tier(chk, srz, ti, fish):
    """Reimplementation of preprocess_dashboard.py's assign_tier(), operating on
    the bids-table column values (chk, srz, ti, fish) instead of a DataFrame row."""
    chin = chk == "Y"
    nook = srz in NOOKSACK_ZONES
    temp = ti == 1
    fish_flag = fish == "fish"

    if chin and nook and temp:
        return "P1"
    if chin and nook and not temp:
        return "P2"
    if fish_flag and not chin and temp:
        return "P2"
    if fish_flag and nook and not chin and not temp:
        return "P3"
    if fish_flag and not nook and temp:
        return "P3"
    if fish_flag and not nook and not temp:
        return "P4"
    return "P5"


def _to_float(v):
    """Parse a CSV cell to float, treating blank/unparseable as missing (None)."""
    if v is None or v == "":
        return None
    try:
        return float(v)
    except ValueError:
        return None


def compute_waterbody_data(csv_path):
    """Stream BID_ZID_LC_20260501.csv once and return (waterbody_bids, waterbody_out):
      waterbody_bids -- set of BIDs with any PositionWaterbody == "Waterbody" row
                        (used by compute_zone_canopy_height to exclude those BIDs
                        from the scored zones rows).
      waterbody_out  -- {bid: {"rid": str, "lc": [9 proportions], "sqft": int, "wt": str}}
                        per-BID in-channel landcover, built directly from this CSV.

    Fix 2 (waterbody_bids NaN groupby): the upstream bid_explorer_data.json's
    waterbody_bids table is built in preprocess_dashboard.py (read-only, RF_Test)
    via `wb_rows.groupby(["BID", "Landcover"])`. pandas groupby drops NaN group
    keys by default. A handful of waterbody rows have a blank/NaN Landcover
    (read as NaN by pandas), and for 4 BIDs that is EVERY waterbody row they
    have -- so those BIDs vanish entirely from the grouped output and never
    reach the JSON. Confirmed against the JSON: this CSV has 1,224 distinct
    waterbody BIDs (PositionWaterbody == "Waterbody"); the JSON's
    waterbody_bids has only 1,220. The 4 missing are L667_2, L677_2, L684_1,
    L105_2 -- each has Zone == "lake" and a blank Landcover on every one of
    its waterbody rows.

    Rather than patch pandas output we cannot re-run (RF_Test is read-only),
    this recomputes waterbody_bids directly from the same CSV already streamed
    for canopy height, using a plain dict accumulation that has no NaN-key
    special case: a blank/unrecognized Landcover value simply doesn't map to
    any of the 9 LC_INDEX slots (matching upstream's treatment of any
    non-LC_ORDER landcover string) and the BID is still retained.
    """
    t0 = time.time()

    waterbody_bids = set()
    # bid -> [rid, sqft_by_lc_index (9 floats), total_sqft, {"river"/"lake" zone strings seen}]
    wb_acc = {}
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        bid_i = header.index("BID")
        rid_i = header.index("RID")
        zone_i = header.index("Zone")
        lc_i = header.index("Landcover")
        sqft_i = header.index("SQFT")
        pw_i = header.index("PositionWaterbody")
        for row in reader:
            if row[pw_i] != "Waterbody":
                continue
            bid = row[bid_i]
            waterbody_bids.add(bid)

            sqft = _to_float(row[sqft_i]) or 0.0
            acc = wb_acc.get(bid)
            if acc is None:
                acc = [row[rid_i], [0.0] * 9, 0.0, set()]
                wb_acc[bid] = acc
            idx = LC_INDEX.get(row[lc_i])
            if idx is not None:
                acc[1][idx] += sqft
            acc[2] += sqft
            zone_val = row[zone_i]
            if zone_val in ("river", "lake"):
                acc[3].add(zone_val)

    waterbody_out = {}
    for bid, (rid, lc_sqft, total_sqft, zone_set) in wb_acc.items():
        lc_pct = [round(v / total_sqft, 2) if total_sqft > 0 else 0.0 for v in lc_sqft]
        wt = "river" if "river" in zone_set else ("lake" if "lake" in zone_set else "")
        waterbody_out[bid] = {
            "rid": rid,
            "lc": lc_pct,
            "sqft": int(round(total_sqft, 0)),
            "wt": wt,
        }

    print(f"    LC pass 1: {len(waterbody_bids):,} waterbody BIDs excluded from "
          f"the scored zones rows; {len(waterbody_out):,} waterbody_bids rows built "
          f"({time.time()-t0:.1f}s)")
    return waterbody_bids, waterbody_out


def compute_zone_canopy_height(csv_path, waterbody_bids):
    """Stream BID_ZID_LC_20260501.csv and return {(bid, z): (sum_h_sqft, sum_sqft)}
    for Forest polygons only, plus the same per (bid, z) Forest SQFT total for
    validation against the upstream zones.lc0 * sqft.

    `waterbody_bids` (from compute_waterbody_data) is the set of BIDs to exclude.
    """
    t0 = time.time()

    sums = {}  # (bid, z) -> [sum_h_sqft, sum_sqft]
    n_rows = 0
    n_forest = 0
    n_reclassed = 0
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        bid_i = header.index("BID")
        zone_i = header.index("Zone")
        lc_i = header.index("Landcover")
        sqft_i = header.index("SQFT")
        comp_i = header.index("Composition")
        ch_i = header.index("CanopyHeight")
        fh_i = header.index("ForestHeight")

        for row in reader:
            n_rows += 1
            z = ZONE_TO_IDX.get(row[zone_i])
            if z is None:
                continue  # river/lake (or unrecognized) zone -- excluded from scored zones
            bid = row[bid_i]
            if bid in waterbody_bids:
                continue

            comp = _to_float(row[comp_i])
            fh = _to_float(row[fh_i])
            landcover = row[lc_i]
            if comp is not None and fh is not None and 0 < fh <= RECLASS_MAX_HT:
                n_reclassed += 1
                landcover = "Shrub/Woodland"  # reclassified -- NOT Forest, regardless of source class
            if landcover != "Forest":
                continue
            n_forest += 1

            sqft = _to_float(row[sqft_i]) or 0.0
            if sqft <= 0:
                continue
            ch = _to_float(row[ch_i])
            height_for_m = ch if ch is not None else fh
            if height_for_m is None:
                continue

            key = (bid, z)
            acc = sums.get(key)
            if acc is None:
                sums[key] = [height_for_m * sqft, sqft]
            else:
                acc[0] += height_for_m * sqft
                acc[1] += sqft

    print(f"    LC pass 2: {n_rows:,} rows, {n_forest:,} Forest polygons "
          f"({n_reclassed:,} reclassified away) in {time.time()-t0:.1f}s total")
    return sums

def load_or_compute_lc_derived(refresh=False):
    """Return (waterbody_bids, waterbody_out, canopy_sums) from LC_CACHE, computing
    them from LC_CSV (and writing the cache) when the cache is missing or refresh=True.
    Shapes are identical to compute_waterbody_data()/compute_zone_canopy_height()."""
    if not refresh and os.path.isfile(LC_CACHE):
        with open(LC_CACHE, "r", encoding="utf-8") as f:
            c = json.load(f)
        waterbody_bids = set(c["waterbody_bids"])
        waterbody_out = c["waterbody_out"]
        canopy_sums = {}
        for k, v in c["canopy_sums"].items():
            bid, z = k.rsplit("|", 1)
            canopy_sums[(bid, int(z))] = v
        print(f"    LC derived data loaded from cache {os.path.relpath(LC_CACHE, SCRIPT_DIR)} "
              f"(source {c.get('source')}, {len(waterbody_out):,} waterbody rows, "
              f"{len(canopy_sums):,} canopy keys)")
        return waterbody_bids, waterbody_out, canopy_sums

    if not os.path.isfile(LC_CSV):
        raise RuntimeError(
            f"Landcover CSV not found at {LC_CSV} and no cache at {LC_CACHE} "
            "(or --refresh-lc-cache was requested). Restore the CSV or the cache."
        )
    waterbody_bids, waterbody_out = compute_waterbody_data(LC_CSV)
    canopy_sums = compute_zone_canopy_height(LC_CSV, waterbody_bids)
    os.makedirs(os.path.dirname(LC_CACHE), exist_ok=True)
    payload = {
        "source": os.path.basename(LC_CSV),
        "source_bytes": os.path.getsize(LC_CSV),
        "waterbody_bids": sorted(waterbody_bids),
        "waterbody_out": waterbody_out,
        "canopy_sums": {f"{bid}|{z}": v for (bid, z), v in canopy_sums.items()},
    }
    with open(LC_CACHE, "w", encoding="utf-8") as f:
        json.dump(payload, f, separators=(",", ":"))
    print(f"    LC derived data written to cache {os.path.relpath(LC_CACHE, SCRIPT_DIR)} "
          f"({os.path.getsize(LC_CACHE)/1e6:.1f} MB)")
    return waterbody_bids, waterbody_out, canopy_sums

# --- Output ---
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "site")

# --- Image mapping: (src_attr_in_html, source_file_path) ---
# The client site ships no images - the shell carries no logo or figures (Task 3/10).
IMAGES = []


MAX_SOLAR_PUSH = 12
MAX_SLOPE_PUSH = 5


def load_s_track_scores(csv_path):
    """Load the whole S-track (rpsn/sols/slps/rpsf/rpsa) per BID from one source.

    Previously rpsf/rpsa came from the upstream JSON while rpsn/sols/slps came
    from this CSV -- two independently-rounded sources for numbers that must
    sum exactly (rpsn + sols + slps + wet == rpsf). Sourcing all five fields
    from this CSV makes the S-track internally consistent from one place.

    Fails loudly if the CSV is missing or doesn't cover every BID in the bids
    table -- a silently half-populated column would be worse than the bug
    this is fixing.
    """
    if not os.path.isfile(csv_path):
        raise RuntimeError(
            f"S-track scores CSV not found: {csv_path}\n"
            "This file is required to build the corrected Score Breakdown "
            "columns (rpsn/sols/slps/rpsf/rpsa). See the comment near "
            "SCORES_CSV in this script for why."
        )

    scores = {}
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            bid = row["BID"]
            rp_s_norm = float(row["RP_S_norm"])
            solar_risk = float(row["solar_risk"])
            slope_risk = float(row["slope_risk"])
            level = (rp_s_norm / 100.0) ** 1.2
            sols = solar_risk * MAX_SOLAR_PUSH * level
            slps = slope_risk * MAX_SLOPE_PUSH * level
            rpsf = float(row["RP_S_final"])
            rpsa = float(row["RP_S_area_pctile"])
            scores[bid] = (rp_s_norm, sols, slps, rpsf, rpsa)

    if len(scores) != EXPECTED_SCORE_ROWS:
        raise RuntimeError(
            f"S-track scores CSV has {len(scores)} rows, expected "
            f"{EXPECTED_SCORE_ROWS}: {csv_path}"
        )

    return scores


def load_fish_override(csv_path):
    """Parse data_overrides/fish_access_override.csv (generated by
    tools/make_fish_override.py -- see FISH_OVERRIDE_CSV comment above).

    Lines starting with '#' are header-comment metadata, not data, and are
    skipped -- one of them declares the expected row count ("# Row count: N"),
    which is checked against the actual number of data rows parsed.

    Returns {bid: (fish_gis, fish_scoring)}. Fails loudly if the file is
    missing or the declared row count doesn't match what's actually in it.
    """
    if not os.path.isfile(csv_path):
        raise RuntimeError(
            f"Fish access override file not found: {csv_path}\n"
            "Regenerate it with `python tools/make_fish_override.py` (see that "
            "script's docstring)."
        )

    declared_count = None
    data_lines = []
    with open(csv_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith("#"):
                if "Row count:" in line:
                    # e.g. "# Row count: 104 (a clean 52/52 swap:"
                    tail = line.split("Row count:", 1)[1].strip()
                    digits = ""
                    for ch in tail:
                        if ch.isdigit():
                            digits += ch
                        else:
                            break
                    if digits:
                        declared_count = int(digits)
                continue
            data_lines.append(line)

    reader = csv.DictReader(data_lines)
    overrides = {}
    for row in reader:
        overrides[row["bid"]] = (row["fish_gis"], row["fish_scoring"])

    if declared_count is not None and len(overrides) != declared_count:
        raise RuntimeError(
            f"{csv_path} declares {declared_count} rows in its header comment "
            f"but has {len(overrides)} data rows -- aborting rather than "
            "applying a mismatched/stale override file. Regenerate with "
            "tools/make_fish_override.py."
        )

    return overrides


def apply_fish_override_and_retier(bid_rows, attr_keys, override_path):
    """Fix 1: apply the GIS-authoritative fish access override, then recompute
    `tier` for every bank using the exact ladder in assign_tier().

    `bid_rows` is the list of per-bid value lists about to be inserted into
    the bids table (vals = [bid, <attr_keys values...>, rpsf, rpsa, sqft,
    rpsn, sols, slps]); mutated in place.

    MANDATORY GUARD: before touching anything, recompute tier for all 30,850
    banks from the UNCHANGED data and assert it reproduces the existing
    `tier` column on 100% of rows. If the ladder is wrong, this must stop
    rather than write incorrect tiers.
    """
    idx_tier = 1 + attr_keys.index("tier")
    idx_srz = 1 + attr_keys.index("srz")
    idx_fish = 1 + attr_keys.index("fish")
    idx_chk = 1 + attr_keys.index("chk")
    idx_ti = 1 + attr_keys.index("ti")

    n = len(bid_rows)

    # --- Mandatory guard: ladder must reproduce 100% of existing tiers as-is ---
    guard_mismatches = []
    for row in bid_rows:
        recomputed = assign_tier(row[idx_chk], row[idx_srz], row[idx_ti], row[idx_fish])
        if recomputed != row[idx_tier]:
            guard_mismatches.append((row[0], row[idx_tier], recomputed))
    guard_pct = 100.0 * (n - len(guard_mismatches)) / n if n else 100.0
    print(f"    Tier-ladder guard: {n - len(guard_mismatches):,}/{n:,} "
          f"({guard_pct:.4f}%) reproduce the existing tier column from unchanged data")
    if guard_mismatches:
        raise RuntimeError(
            f"Tier-ladder guard FAILED: {len(guard_mismatches)} row(s) do not "
            f"reproduce the existing tier column (e.g. {guard_mismatches[:5]}). "
            "The reimplemented ladder does not match assign_tier() in "
            "preprocess_dashboard.py -- STOPPING rather than writing tiers "
            "computed from a wrong ladder. See Fix 1c guard requirement."
        )

    # --- Apply the fish-access override ---
    overrides = load_fish_override(override_path)
    bid_to_row = {row[0]: row for row in bid_rows}
    missing = [bid for bid in overrides if bid not in bid_to_row]
    if missing:
        raise RuntimeError(
            f"{len(missing)} BID(s) in {override_path} are not present in the "
            f"bids table (e.g. {missing[:5]}) -- aborting rather than applying "
            "a partially-matched override."
        )

    tier_before = {row[0]: row[idx_tier] for row in bid_rows}

    for bid, (fish_gis, _fish_scoring) in overrides.items():
        bid_to_row[bid][idx_fish] = fish_gis

    # --- Recompute tier for every bank (not just the overridden 104) ---
    n_retiered = 0
    for row in bid_rows:
        new_tier = assign_tier(row[idx_chk], row[idx_srz], row[idx_ti], row[idx_fish])
        if new_tier != row[idx_tier]:
            n_retiered += 1
            row[idx_tier] = new_tier

    from collections import Counter
    tier_counts_before = Counter(tier_before.values())
    tier_counts_after = Counter(row[idx_tier] for row in bid_rows)

    print(f"    Fish access override: {len(overrides)} BID(s) corrected to the "
          f"GIS-authoritative value ({os.path.basename(override_path)})")
    print(f"    Tiers recomputed: {n_retiered} bank(s) changed tier as a result")
    print("    Tier counts before -> after:")
    for t in ("P1", "P2", "P3", "P4", "P5"):
        print(f"      {t}: {tier_counts_before.get(t, 0):,} -> {tier_counts_after.get(t, 0):,}")

    return {
        "guard_pct": guard_pct,
        "override_count": len(overrides),
        "n_retiered": n_retiered,
        "tier_counts_before": dict(tier_counts_before),
        "tier_counts_after": dict(tier_counts_after),
    }


def build_sqlite(bid_json_path, sqlite_path, main_json_path):
    """Convert bid_explorer_data.json to bids.sqlite."""
    t0 = time.time()
    print("  Converting bid_explorer_data.json -> bids.sqlite ...")
    with open(bid_json_path, "r", encoding="utf-8") as f:
        d = json.load(f)

    if os.path.exists(sqlite_path):
        os.remove(sqlite_path)

    conn = sqlite3.connect(sqlite_path)
    conn.execute("PRAGMA journal_mode=OFF")
    conn.execute("PRAGMA synchronous=OFF")

    conn.execute("""
        CREATE TABLE bids (
            bid TEXT PRIMARY KEY,
            rid TEXT,
            wet REAL,
            tier TEXT, srz TEXT, fish TEXT, chk TEXT, mgr TEXT,
            bfw TEXT, bft REAL, hmz INTEGER, zon TEXT,
            cua TEXT, jur TEXT,
            ti INTEGER, tic TEXT,
            fi INTEGER, fic TEXT,
            si INTEGER, sic TEXT,
            ai INTEGER,
            sal INTEGER, sps TEXT,
            asp REAL, af REAL,
            str TEXT, ss INTEGER, zc INTEGER, pc INTEGER, dom TEXT, wt TEXT,
            cx REAL, cy REAL, pf REAL, ps REAL, ph REAL,
            mc REAL, mh REAL, rpsf REAL, rpsa REAL,
            sqft REAL,
            rpsn REAL, sols REAL, slps REAL
        )
    """)
    # One zone table. lc0..lc8 are landcover PROPORTIONS (area = lcN * sqft). Zones 0-4 are
    # the scored buffer zones; z = 5 is the channel/lake zone and carries NULL comp..cht.
    # It replaces the old JSON-text `zones.data` column and the derived per-zone-area
    # stats table, which duplicated the same numbers as areas. cht is the forest-area-weighted canopy
    # height computed from the landcover CSV (see compute_zone_canopy_height).
    conn.execute("""
        CREATE TABLE zones (
            bid TEXT NOT NULL, z INTEGER NOT NULL, sqft REAL,
            lc0 REAL, lc1 REAL, lc2 REAL, lc3 REAL, lc4 REAL,
            lc5 REAL, lc6 REAL, lc7 REAL, lc8 REAL,
            comp REAL, ht REAL, den REAL, zrp REAL, cstd REAL, cht REAL,
            PRIMARY KEY (bid, z)
        ) WITHOUT ROWID
    """)
    conn.execute("""
        CREATE TABLE waterbody_bids (
            bid TEXT PRIMARY KEY,
            rid TEXT,
            lc TEXT,    -- JSON-encoded array of 9 landcover proportions
            sqft INTEGER,
            wt TEXT     -- 'river' or 'lake'
        )
    """)

    # Scoring Lab sample polygons (D1_Forest only, the only domain the Lab charts read) and
    # small named constants. These replace dashboard_data.json on the client page.
    conn.execute("""
        CREATE TABLE lab_sample (
            m REAL, d REAL, c REAL, fh REAL, spth REAL, sqft REAL, domain TEXT, zone TEXT
        )
    """)
    conn.execute("CREATE TABLE lab_meta (key TEXT PRIMARY KEY, value TEXT)")

    # Field order matching the CREATE TABLE
    attr_keys = [
        'rid',
        'wet',
        'tier', 'srz', 'fish', 'chk', 'mgr',
        'bfw', 'bft', 'hmz', 'zon',
        'cua', 'jur',
        'ti', 'tic', 'fi', 'fic', 'si', 'sic', 'ai',
        'sal', 'sps',
        'asp', 'af',
        'str', 'ss', 'zc', 'pc', 'dom', 'wt',
        'cx', 'cy', 'pf', 'ps', 'ph',
        'mc', 'mh',
    ]
    bool_keys = {'hmz', 'ti', 'fi', 'si', 'ai', 'sal'}
    # +1 bid, +1 sqft, +5 rpsn/sols/slps/rpsf/rpsa (all from SCORES_CSV, one source)
    placeholders = ",".join(["?"] * (7 + len(attr_keys)))

    s_track = load_s_track_scores(SCORES_CSV)
    missing_bids = [bid for bid in d["bids"] if bid not in s_track]
    if missing_bids:
        raise RuntimeError(
            f"{len(missing_bids)} BID(s) in bid_explorer_data.json have no "
            f"match in {SCORES_CSV} (e.g. {missing_bids[:5]}). The S-track "
            "join must cover every BID -- aborting rather than shipping a "
            "half-populated rpsn/sols/slps column."
        )

    # Zone array layout: [lc0..lc8 (proportions), sqft, comp, ht, den, zrp, comp_std]
    Z_SQFT, Z_COMP, Z_HT = 9, 10, 11
    SCORED_ZONES = 5  # indices 0-4; index 5 is the channel/lake zone, excluded

    waterbody_bids_set, waterbody_out, canopy_sums = load_or_compute_lc_derived(refresh=REFRESH_LC_CACHE)

    bid_rows = []
    zone_rows = []
    # Validation: my Forest SQFT per (bid, z) vs. the upstream lc0_sqft (also Forest
    # area, computed after the same reclassification) -- see spec section on the
    # three replicated rules. A poor match means one of them is wrong.
    match_within_1pct = 0
    match_rounding_aware = 0
    n_validated = 0
    worst_abs = 0.0
    worst_abs_key = None
    worst_rel = 0.0
    worst_rel_key = None
    cht_populated = 0
    cht_null = 0
    cht_null_despite_forest = 0
    cht_sum = 0.0
    cht_clamped = 0
    for bid in d["bids"]:
        a = d["attrs"].get(bid, {})
        zones = d["zones"].get(bid, [])

        total_sqft = 0.0
        for i, z in enumerate(zones):
            if z is None:
                continue
            if i >= SCORED_ZONES or len(z) <= Z_HT:
                # Channel/lake zone: [lc0..lc8, sqft] only.
                zone_rows.append((bid, i, float(z[Z_SQFT] or 0.0),
                                  *[float(z[k] or 0.0) for k in range(9)],
                                  None, None, None, None, None, None))
                continue
            z_sqft = float(z[Z_SQFT] or 0.0)
            total_sqft += z_sqft
            lc0_sqft = float(z[0] or 0.0) * z_sqft

            acc = canopy_sums.get((bid, i))
            my_forest_sqft = acc[1] if acc else 0.0
            # NULL is gated on lc0_sqft (the existing "this zone has no Forest" sentinel
            # used everywhere else in the app, e.g. statsCompByZone's forestSqft), not on
            # our own exact Forest sqft sum: a sliver of Forest area that upstream's
            # 2-decimal-place proportion rounding collapses to 0% is already treated as
            # "no forest" by every other forest-only metric in the dashboard (comp), so
            # cht must agree with it rather than showing a number the rest of the UI
            # calls "no forest".
            if lc0_sqft > 0 and acc and acc[1] > 0:
                cht = acc[0] / acc[1]
                # Fix 3: a couple of Forest polygons carry a negative ForestHeight in
                # the source (BID_ZID_LC_20260501.csv), which propagates into this
                # forest-area-weighted average. A negative canopy height is physically
                # impossible, so clamp the DISPLAY value to 0 here -- this is a
                # display-layer clamp over a source-data artifact, not a fix to the
                # source data itself (approved by the project lead).
                if cht < 0:
                    cht = 0.0
                    cht_clamped += 1
                cht_populated += 1
                cht_sum += cht
            else:
                cht = None
                cht_null += 1
                # Vanishingly rare (see build summary): a zone upstream counts as having
                # Forest area, but every Forest polygon in it is missing BOTH CanopyHeight
                # and ForestHeight, so no height value exists to average.
                if lc0_sqft > 0:
                    cht_null_despite_forest += 1

            # Validate against lc0_sqft wherever either side thinks there's Forest area.
            #
            # lc0_sqft is itself upstream's landcover PROPORTION (rounded to 2 decimals
            # in preprocess_dashboard.py, e.g. `round(pct, 2)`) multiplied back out by
            # z_sqft -- it is a quantized proxy for Forest area, not an exact figure. A
            # zone with a sliver of Forest (e.g. 9 sqft of 61,460) rounds to a 0.00
            # proportion and hence lc0_sqft == 0, while our direct SQFT sum is exact.
            # So we additionally compute what lc0_sqft *would* be if built from our own
            # (correct) Forest sqft through that same rounding step, and treat a match
            # there as the real proof the three replicated rules line up -- the raw
            # relative-difference figures are reported too, for transparency, but they
            # are expected to look poor purely from this quantization, not from a bug.
            if lc0_sqft > 0 or my_forest_sqft > 0:
                n_validated += 1
                abs_diff = abs(my_forest_sqft - lc0_sqft)
                rel_diff = abs_diff / lc0_sqft if lc0_sqft > 0 else (0.0 if abs_diff == 0 else float("inf"))
                if rel_diff <= 0.01:
                    match_within_1pct += 1
                if abs_diff > worst_abs:
                    worst_abs = abs_diff
                    worst_abs_key = (bid, i)
                if rel_diff > worst_rel:
                    worst_rel = rel_diff
                    worst_rel_key = (bid, i)

                expected_lc0 = round(my_forest_sqft / z_sqft, 2) * z_sqft if z_sqft > 0 else 0.0
                if abs(expected_lc0 - lc0_sqft) < 1.0:
                    match_rounding_aware += 1

            zone_rows.append((
                bid, i, z_sqft,
                *[float(z[k] or 0.0) for k in range(9)],
                float(z[Z_COMP] or 0.0), float(z[Z_HT] or 0.0),
                float(z[12] or 0.0), float(z[13] or 0.0), float(z[14] or 0.0),
                cht,
            ))

        vals = [bid]
        for k in attr_keys:
            v = a.get(k)
            if k in bool_keys:
                v = 1 if v else 0
            vals.append(v)
        rpsn, sols, slps, rpsf, rpsa = s_track[bid]
        vals.append(rpsf)
        vals.append(rpsa)
        vals.append(total_sqft)
        vals.extend([rpsn, round(sols, 3), round(slps, 3)])
        bid_rows.append(vals)

    # Fix 1: GIS-authoritative fish-access override + tier recompute (includes
    # the mandatory 100% ladder guard). Mutates bid_rows in place.
    fish_override_summary = apply_fish_override_and_retier(bid_rows, attr_keys, FISH_OVERRIDE_CSV)

    conn.executemany(f"INSERT INTO bids VALUES ({placeholders})", bid_rows)
    conn.executemany("INSERT INTO zones VALUES (" + ",".join(["?"] * 18) + ")", zone_rows)

    # Waterbody (in-channel) BIDs -- Fix 2: built directly from BID_ZID_LC_20260501.csv
    # (waterbody_out, from compute_waterbody_data above) rather than trusting the
    # upstream JSON's waterbody_bids table, which silently drops 4 BIDs to a pandas
    # groupby-on-NaN bug. See compute_waterbody_data()'s docstring.
    wb_rows = [
        (bid, w.get("rid", ""), json.dumps(w.get("lc", [0.0] * 9)),
         int(w.get("sqft", 0)), w.get("wt", ""))
        for bid, w in waterbody_out.items()
    ]
    if wb_rows:
        conn.executemany("INSERT INTO waterbody_bids VALUES (?,?,?,?,?)", wb_rows)

    # --- lab_sample + lab_meta (from the upstream dashboard_data.json and from bids.sols) ---
    with open(main_json_path, "r", encoding="utf-8") as f:
        main_d = json.load(f)
    sample = [p for p in main_d.get("sensitivity", {}).get("sample_polygons", [])
              if p.get("domain") == "D1_Forest"]
    conn.executemany(
        "INSERT INTO lab_sample VALUES (?,?,?,?,?,?,?,?)",
        [(p.get("M"), p.get("D"), p.get("C"), p.get("FH"), p.get("SPTH"), p.get("SQFT"),
          p.get("domain"), str(p.get("zone"))) for p in sample],
    )
    sols_vals = sorted(v[0] for v in conn.execute("SELECT sols FROM bids WHERE sols IS NOT NULL"))
    def pct(p):
        if not sols_vals:
            return None
        k = (len(sols_vals) - 1) * p / 100.0
        lo, hi = int(k), min(int(k) + 1, len(sols_vals) - 1)
        return round(sols_vals[lo] + (sols_vals[hi] - sols_vals[lo]) * (k - lo), 4)
    n = len(sols_vals)
    mean = sum(sols_vals) / n if n else None
    std = (sum((v - mean) ** 2 for v in sols_vals) / n) ** 0.5 if n else None
    solar_push_stats = {
        "count": n, "mean": round(mean, 4), "std": round(std, 4),
        "min": round(sols_vals[0], 4), "p10": pct(10), "p25": pct(25), "p50": pct(50),
        "p75": pct(75), "p90": pct(90), "max": round(sols_vals[-1], 4),
    }
    # Derived from the newest build input, not wall-clock time, so that identical inputs
    # produce a byte-identical database (the shipped filename is a content hash).
    newest_input = max(os.path.getmtime(p) for p in (bid_json_path, main_json_path, SCORES_CSV, FISH_OVERRIDE_CSV))
    generated = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(newest_input))
    conn.executemany("INSERT INTO lab_meta VALUES (?, ?)", [
        ("solar_push_stats", json.dumps(solar_push_stats)),
        ("generated", json.dumps(generated)),
        ("source_meta", json.dumps(main_d.get("meta", {}))),
    ])
    print(f"    lab_sample: {len(sample):,} D1_Forest polygons; solar_push_stats from sols: "
          f"mean={solar_push_stats['mean']}, p50={solar_push_stats['p50']}")

    # No secondary indexes: every dashboard query is a filtered scan or GROUP BY over
    # 30,850 rows (~1 ms either way); the six old indexes cost 3.25 MB of download.
    conn.commit()
    conn.execute("VACUUM")

    # Verify
    count = conn.execute("SELECT COUNT(*) FROM bids").fetchone()[0]
    zone_count = conn.execute("SELECT COUNT(*) FROM zones").fetchone()[0]
    zs_count = conn.execute("SELECT COUNT(*) FROM zones WHERE z <= 4").fetchone()[0]
    wb_count = conn.execute("SELECT COUNT(*) FROM waterbody_bids").fetchone()[0]
    acres = conn.execute("SELECT SUM(sqft)/43560.0 FROM bids").fetchone()[0]
    s_track_count = conn.execute(
        "SELECT COUNT(*) FROM bids WHERE rpsn IS NOT NULL AND sols IS NOT NULL AND slps IS NOT NULL "
        "AND rpsf IS NOT NULL AND rpsa IS NOT NULL"
    ).fetchone()[0]
    conn.close()

    sz_mb = os.path.getsize(sqlite_path) / (1024 * 1024)
    print(f"    {count} BIDs, {zone_count} zone rows (all), {zs_count} scored zone rows, "
          f"{wb_count} waterbody_bids rows, {acres:,.0f} acres, {sz_mb:.1f} MB in {time.time()-t0:.1f}s")
    print(f"    S-track join: {s_track_count}/{count} BIDs got rpsn/sols/slps/rpsf/rpsa from {os.path.basename(SCORES_CSV)}")
    print(f"    Fix 2 (waterbody_bids NaN groupby): {wb_count} rows shipped "
          f"(was 1,220 from the upstream JSON before this fix; the 4 recovered "
          f"BIDs are L667_2, L677_2, L684_1, L105_2)")

    match_pct = (match_within_1pct / n_validated * 100) if n_validated else 100.0
    match_pct_rounded = (match_rounding_aware / n_validated * 100) if n_validated else 100.0
    print(f"    cht Forest-SQFT validation vs. lc0_sqft (raw): {match_within_1pct:,}/{n_validated:,} "
          f"({match_pct:.2f}%) rows within 1% rel; worst abs diff {worst_abs:,.1f} sqft "
          f"at {worst_abs_key}; worst rel diff {worst_rel*100:.2f}% at {worst_rel_key}")
    print(f"    cht Forest-SQFT validation, rounding-aware (lc0_sqft is upstream's Forest "
          f"PROPORTION rounded to 2dp, times z_sqft -- a sliver of Forest rounds to 0%): "
          f"{match_rounding_aware:,}/{n_validated:,} ({match_pct_rounded:.2f}%) match to "
          f"<1 sqft once our exact Forest sqft is put through that same rounding step")
    if match_pct_rounded < 99.0:
        raise RuntimeError(
            f"zones.cht Forest-SQFT validation match rate {match_pct_rounded:.2f}% "
            "(rounding-aware) is below 99% -- one of the reclassification/waterbody/"
            "zone-mapping rules replicated from preprocess_dashboard.py does not match. "
            "Aborting rather than shipping a mismatched canopy-height aggregate."
        )
    cht_mean = (cht_sum / cht_populated) if cht_populated else None
    cht_mean_str = f"{cht_mean:.2f} ft" if cht_mean is not None else "n/a"
    print(f"    cht (canopy height, forest-area weighted): {cht_populated:,} rows populated, "
          f"{cht_null:,} rows NULL (no forest), mean={cht_mean_str}")
    if cht_null_despite_forest:
        print(f"    NOTE: {cht_null_despite_forest} of those NULLs are zones where "
              "lc0_sqft > 0 but every Forest polygon in the zone is missing both "
              "CanopyHeight and ForestHeight (no height value exists to average)")
    if cht_clamped:
        print(f"    cht clamp (Fix 3): {cht_clamped} (bid, zone) row(s) had a negative "
              "forest-area-weighted canopy height (source ForestHeight is negative for "
              "a couple of Forest polygons) -- clamped to 0 ft for display")
    return count


def main():
    global REFRESH_LC_CACHE
    REFRESH_LC_CACHE = "--refresh-lc-cache" in sys.argv

    t_start = time.time()
    print("Building multi-file dashboard site...")
    print(f"  Output: {OUTPUT_DIR}")

    # --- Read source HTML ---
    with open(HTML_PATH, "r", encoding="utf-8") as f:
        html = f.read()
    print(f"  Read dashboard.html: {len(html):,} chars")

    # --- 6. Swap React dev builds for production ---
    # The source loads the development UMD builds, which carry helpful warnings while
    # editing but are substantially larger and slower. The shipped client site should
    # not pay that cost.
    for mod in ("react", "react-dom"):
        html = html.replace(f"umd/{mod}.development.js", f"umd/{mod}.production.min.js")
    print("  Swapped React to production builds")

    # --- 7. Update server requirement comment ---
    html = html.replace(
        "Note: Chrome blocks fetch() from file:// URLs. Use the server above or Firefox.",
        "Multi-file site -- serve via HTTP (python -m http.server) or deploy to GitHub Pages.",
    )

    # --- Create output directories ---
    for subdir in ["", "data"]:
        os.makedirs(os.path.join(OUTPUT_DIR, subdir), exist_ok=True)

    # --- Build SQLite database, gzip it, content-hash the filename ---
    data_dir = os.path.join(OUTPUT_DIR, "data")
    for stale in glob.glob(os.path.join(data_dir, "bids.*.sqlite.gz")) + [os.path.join(data_dir, "bids.sqlite")]:
        if os.path.exists(stale):
            os.remove(stale)
    raw_path = os.path.join(data_dir, "bids.sqlite")
    build_sqlite(BID_JSON, raw_path, MAIN_JSON)
    with open(raw_path, "rb") as f:
        raw = f.read()
    gz_bytes = gzip.compress(raw, compresslevel=9, mtime=0)
    digest = hashlib.sha1(gz_bytes).hexdigest()[:8]
    gz_name = f"bids.{digest}.sqlite.gz"
    with open(os.path.join(data_dir, gz_name), "wb") as f:
        f.write(gz_bytes)
    os.remove(raw_path)
    print(f"  Wrote data/{gz_name}: {len(gz_bytes)/1e6:.2f} MB gzipped (from {len(raw)/1e6:.1f} MB raw)")

    # --- Point the page at the hashed file (DB_URL literal + preload link) ---
    n_refs = html.count("data/bids.sqlite.gz")
    if n_refs < 2:
        raise RuntimeError(f"expected DB_URL literal and preload link to reference data/bids.sqlite.gz, found {n_refs}")
    html = html.replace("data/bids.sqlite.gz", f"data/{gz_name}")

    # --- Write index.html ---
    out_html = os.path.join(OUTPUT_DIR, "index.html")
    with open(out_html, "w", encoding="utf-8") as f:
        f.write(html)
    html_kb = os.path.getsize(out_html) / 1024
    print(f"  Wrote index.html: {html_kb:.0f} KB")

    # --- Summary ---
    total_size = sum(
        os.path.getsize(os.path.join(dp, f))
        for dp, dn, fns in os.walk(OUTPUT_DIR) for f in fns
    )
    print(f"\nSite built in {time.time()-t_start:.1f}s")
    print(f"  Total size: {total_size/(1024*1024):.1f} MB across all files")
    print(f"  Output: {OUTPUT_DIR}")
    print("  Serve with: python -m http.server 8080")


if __name__ == "__main__":
    main()
