"""One-off generator: data_overrides/gnis_names.csv

The 3DHP GNIS stream name per bank, for the bids.gn column (BID Query stream filter,
#stream/ deep links, Bank Explorer's Location card). The upstream bid_explorer_data.json
carries no stream name -- its `str` is the 3DHP feature type -- so the name comes from the
GIS feature layer export.

Like make_fish_override.py, this is run by hand whenever the source changes. Its output is
committed and read by build_client_site.py at every build, which keeps the 40 MB (and
gitignored) TP_Split_JOIN_20260507.csv out of the build's dependency graph.

Usage (from Final_Build/):
    python tools/make_gnis_names.py

Reads:
    TP_Split_JOIN_20260507.csv   (GIS feature layer export; BID, GNIS_NAME)

Writes:
    data_overrides/gnis_names.csv
        columns: bid,gnis_name,reach_len_ft
        every BID in the export; gnis_name blank when unnamed; reach_len_ft is the bank's
        reach length (StreamLengthFtRID, shared by both banks of a reach), blank on lakes
        and the few river-polygon reaches the export carries no length for.
"""
import csv
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
SOURCE_CSV = os.path.join(ROOT_DIR, "TP_Split_JOIN_20260507.csv")
OUT_PATH = os.path.join(ROOT_DIR, "data_overrides", "gnis_names.csv")


def main():
    names, lengths = {}, {}
    with open(SOURCE_CSV, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            bid, name = row["BID"], (row["GNIS_NAME"] or "").strip()
            if bid in names and names[bid] != name:
                raise SystemExit(f"{bid} carries two GNIS names in {SOURCE_CSV}: "
                                 f"{names[bid]!r} and {name!r}")
            names[bid] = name
            ln = (row["StreamLengthFtRID"] or "").strip()
            lengths[bid] = f"{float(ln):.1f}" if ln else ""
    with open(OUT_PATH, "w", encoding="utf-8", newline="") as f:
        f.write("# Generated by tools/make_gnis_names.py from TP_Split_JOIN_20260507.csv. "
                "Do not edit by hand.\n")
        w = csv.writer(f)
        w.writerow(["bid", "gnis_name", "reach_len_ft"])
        for bid in sorted(names):
            w.writerow([bid, names[bid], lengths[bid]])
    named = sum(1 for v in names.values() if v)
    print(f"wrote {OUT_PATH}: {len(names):,} BIDs, {named:,} named, "
          f"{len({v for v in names.values() if v})} distinct names")


if __name__ == "__main__":
    main()
